name: .NET + NuGet

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  pack-push:
    env:
      CAMINHO_PROJETO: ./Melo.Distancias/Melo.Distancias.csproj

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup.NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Generate build number
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}        

    # - name: Print new build number
    #   run: echo "Build number is $BUILD_NUMBER"

    - name: Geração do package
      run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate

    
        
