name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  Publish-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # dotnet-version: ['5.0.x', '6.0.x']
        dotnet-version: ['5.0.x']
    
    env:
      PROJECT_PATH: ./Melo.Distancias/*.csproj
      PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          #Fetch all commits
          fetch-depth: 0

      - name: Set environment variables
        run: |
          cat >> $GITHUB_ENV << EOF
          VERSION=${GITHUB_REF##*/}
          EOF

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Edit the correct version format (Python)
        run: |
          import os
          import re
          RELEASE_VERSION = "${{ env.VERSION }}"
          RELEASE_SPLIT_VERSION = re.split("v", RELEASE_VERSION)
          env_file = os.getenv('GITHUB_ENV')
          with open(env_file, "a") as myfile:
            myfile.write("NUGET_VERSION=" + RELEASE_SPLIT_VERSION[1])
        shell: python

      - name: Build Project and Generate Package
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release -p:PackageVersion=${{ env.NUGET_VERSION }} -o ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Push Package on NuGet
        run: dotnet nuget push '${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate